#!/bin/bash
# ajb June 2018 main driver script for running a continental HRDPS or GDPS visualization run
# Call this as do-rasp-run-continental.sh

git pull  # this works because I did git config credential.helper store

# This line adds two directories to the PATH environment variable.
# The aws-utils directory, and the .local/bin directory which contains user-specific binaries.
PATH=$PATH:/home/ubuntu/canadarasp/aws-utils:/home/ubuntu/.local/bin

# These lines read the instance ID, shutdown flag, model type, and web server name
MY_INSTANCE_ID=`get-my-instance-id.sh`
SHUTDOWN=`aws-read-tag.sh $MY_INSTANCE_ID shutdown`
SHUTDOWN=${SHUTDOWN:-true}
MODEL=`aws-read-tag.sh $MY_INSTANCE_ID model`
WEBSERVERNAME=`aws-read-tag.sh $MY_INSTANCE_ID webserver`
export WEBSERVERNAME=${WEBSERVERNAME:-"WEB PROD V9"}
echo Will upload data to $WEBSERVERNAME

/home/ubuntu/canadarasp/setup-lisp.sh

if [ $SHUTDOWN == "true" ]; then
 echo Going to shutdown after run
else
 echo Not going to shutdown after run
fi

if [ $MODEL == "none" ]; then 
 echo No model specified, debugging mode enabled
 exit 1;
fi

# The HRDPS ROT files were renamed to HRDPS files,
# so we can just process them pretending that they are HRDPS files (I think)
if [ $MODEL == "hrdps_rot" ]; then
    echo Running HRDPS from rotated latlon grid renaming back to hrdps
    MODEL="hrdps"
fi

export MODEL=${MODEL:-"gdps"}

# These lines attach and mount the download box for the specified model.
# The attach-download-box.sh script attaches the download box to the instance,
# and the mount-download-box.sh script mounts the download box to the /download-box directory.
echo Attaching and mounting download-box-$MODEL
source /home/ubuntu/canadarasp/aws-utils/attach-download-box.sh
source /home/ubuntu/canadarasp/aws-utils/mount-download-box.sh /download-box

# These lines move the downloaded data from the download box to the local disk.
# The model-parameters.sh script sets the model parameters for the specified model,
# the guess-time.sh script guesses the forecast time,
# and the setup-drives.sh script sets up the disk drives for the model run.
# The cp -R * /mnt/input/$MODEL command copies all the downloaded data to
# the /mnt/input/$MODEL directory, and the sync command flushes the file system buffers to
# ensure that all data is written to disk.
# The unmount-download-box.sh script unmounts the download
echo Moving downloaded data to local disk starting at `date`
echo Running RASP for model $MODEL, SHUTDOWN=$SHUTDOWN
source ./model-parameters.sh $MODEL
source ./guess-time.sh $MODEL
./setup-drives.sh
df
cd /download-box
cp -R * /mnt/input/$MODEL
sync
cd /home/ubuntu/canadarasp/continental-test
df
source /home/ubuntu/canadarasp/aws-utils/unmount-download-box.sh
source /home/ubuntu/canadarasp/aws-utils/delete-download-box.sh
echo Done moving downloaded data to local disk at `date`

# generate HRDPS plots and windgrams
if [ -z $NOPLOT ]; then # if string is NULL (length equal to 0), then we do want to plot
 echo "generate HRDPS and windgram plots"
 echo "./do-hrdps-plots-continental.sh $YEAR $MONTH $DAY $HOUR > hrdps-plots.log 2>&1"
 # Rename log file
 mv hrdps-plots.log hrdps-plots.log.old
 # `> hrdps-plots.log`: This redirects the standard output of the script to the
 # hrdps-plots.log file. Any output generated by the script will be written to this file
 # instead of being displayed on the screen.
 # `2>&1`: This redirects the standard error output of the script to the same file
 # as the standard output. This ensures that any error messages generated by the script
 # will also be written to the hrdps-plots.log file.
 ./do-hrdps-plots-continental.sh $YEAR $MONTH $DAY $HOUR > hrdps-plots.log 2>&1
fi

echo "Finished at `date`"
if [ $SHUTDOWN == "true" ] ; then
  echo "Shutting down 30 seconds"
  sleep 30
  # Shut down the instance immediately
  sudo shutdown -h now
fi
